---
title: "Linguistics"
description: "The study of language as a human faculty."
---

The study of language as a human faculty.
Linguistics describes language phenomena of
all sorts, from the individual sound through complete discourses. Further, linguistics is a descriptive discipline. Contemporary linguists do not attempt to prescribe how language is used; rather
they describe how language is used, primarily by
native speakers but also in applied areas such as
sociolinguistics and English as a Second Language, as used by nonnative speakers as well. This
article will begin with a general discussion of language phenomena, then focus specifically onrecent and contemporary applications of linguistics
to rhetoric and composition studies. Much of the
discussion is based on Raskin and Weiser (1987).
The linguistic disciplines of phonetics and
phonology study the phenomenon of sound in
language. Phonetics is concerned with the empirical analysis of sound and includes the segmentation of the flow of sounds in speech into discrete
units, the inventorying of the sounds of a particular language, the description of each sound, and
the description of the elements of pronunciation.
Phonology is a theoretical discipline that studies
3 8 6 LETTERATURIZZAZIONE
the sound patterns in a language. Working from
the descriptions of individual sounds described
by phonetics, phonology is concerned with the
distinction between similar sounds (for example,
the subtle differences between aspirated and
unaspirated sounds such as the p in pin and in
spin, and the more obvious differences such as
that between the initial sounds in the words pin
and bin), the set of "permissible" sound patterns
in a particular language (for instance, the absence
of the initial combination of "cj" or "ck" in
English, though the latter combination is permissible in the middle or end of words, as in chicken
or check), and the range of variation in sound
(for example, sounds that are phonetically similar enough to be accepted as the same, accounting for a native speaker's ability to understand a
variety of accents and dialects).
Morphology is concerned with the smallest
meaningful units of language, those which enable
language-users to understand complex individual
words. The smallest meaningful parts are called
morphemes. Words are composed of one or
more morphemes. Words such as walk, table, desire, frame, and elephant all are single-morpheme
words; that is, none can be divided into smaller
meaningful units. Words such as walking, tables,
desirable, reframe, and elephantine consist of
two morphemes each, while undesirable and re-
framed are made up of three morphemes. The division of words into morphemes is thus unrelated
to the division of words into syllables because,
as the examples of table, desire, and elephant
demonstrate, multisyllabic words may nevertheless consist of only a single morpheme. Similarly,
the word dogs consists of only one syllable but
two morphemes, dog plus the plural marker s.
Thus the distinction between a word and a morpheme is that a word is the minimal meaningful
unit that can be used alone within the context of
ordinary speech. Such a morpheme is sometimes
referred to as a lexical or free morpheme. Other
morphemes, called grammatical or bound morphemes, such as most prefixes and suffixes and
plural markers, cannot stand alone in this way.
Syntax refers to the system of rules that describe how words are combined into phrases and
sentences. Each sentence can be analyzed syntactically by identifying all the phrases that compose
it and all the words that constitute each phrase.
The analysis of sentences by syntactic rules
underlies the concepts of grammaticality and
ungrammaticality—that is, whether or not a sentence is considered by native speakers to be a
possible sentence of their language. Contemporary syntactic theory has been most heavily influenced by the work of Noam Chomsky. In Syntactic Structures (1957), Chomsky proposed a set
of rules for describing syntax that formed the
basis of generative grammar—a grammar, that
is, a system of rules—which can explain or generate the structures of all the grammatical sentences of a language. The key rules of generative
grammar, the phrase structure rules, can account
for a wide variety of syntactic patterns, but the
addition of transformational rules helpedaccount for some more complex structures such as
negatives and passives. The main contribution of
transformations has been to allow the identification of two levels of syntax: the deep structure,
assumed to be the result of the application of the
phrase structure rules of generative grammar,
and the surface structure, which results from the
application of transformations. Thus the deep
structure of "The dog chased the cat" and "The
cat was chased by the dog" are assumed to be the
same, and the difference in their surface structure
is attributed to the application of the passive
transformation to the sentence generated by the
insertion of lexical items into the noun phrase/
verb phrase structure of the sentence.
A problem with Chomsky's early theory is
that it provided rules for generating not only
grammatical sentences but also sentences like his
famous " * Colorless green ideas sleep furiously"
(the asterisk is a conventional marker in linguistics for nongrammatical sentences). In his Aspects
of the Theory of Syntax (1965), Chomsky revised
transformational grammar by adding additional
rules that accounted for features or properties
such as animate, human, singular, and so on for
nouns and similar features for other words and
combinatorial and selection restriction rules that
govern grammatical combinations.
A final point to be made here about syntax
and one which has implications for the applications of syntax to rhetoric and composition
discussed later is that all languages allow for
clauses and sentences to be embedded within
one another.
Semantics differs from the linguistic disciplines discussed in the preceding paragraphs.
While phonetics, phonology, morphology, and
syntax are concerned with linguistic structures,
semantics is concerned with the study of meaning in language. Thus semantics encompasses a
variety of linguistic structures, from the morpheme, which is the minimal meaningful unit in
language, through the text or discourse. Early semantic studies focused primarily on word
meaning, with emphasis on the analysis of semantic features. These abstract features, such as
human, male, and adult, allowed for words such
as man, woman, boy, and girl to be described
according to whether or not they possessed each
feature. Thus while each of these four words
would be described as "+Human," man and boy
would be described as "+Male," woman andgirl
as "-Male," man and woman as "+Adult," and
boy and girl as "-Adult." Feature analysis is most
adequate at describing meaning when it isapplied to words with clear, distinct meanings; it is
less successful at describing words whose meanings cannot easily be identified in binary features.
Words that describe colors are typical examples:
It is difficult to determine the features of blue, for
example, that would allow one to distinguish it
from other colors, both those very different such
as yellow and those fairly similar such as violet
or blue-green.
A second semantic approach to word meaning focuses on the relations of words to one another. The four commonly studied relationships
are synonymy, the relationship among words
with identical or very similar meanings; antono-
my, the relationship between two words with
opposite meanings; homonymy, words with the
same spelling and pronunciation but different
and unrelated meanings; and polysemy, words
with related though different meanings. Unlike
synonyms and antonyms, homonyms do not
share semantic features: bear referring to the
animal, bear meaning to give birth, and bear
meaning to tolerate demonstrate this. Homonyms and polysemous words may create ambiguity, as in a sentence like "The bill is large," in
which bill may refer to the beak of a bird, a part
of a cap, or the slip of paper indicating the cost
of a purchase. Contextual semantics, discussed
later, attempts to address this kind of ambiguity.
Another area of semantic study is sentence
meaning. The work of Katz and Fodor (1963)
is foundational. Associates of Chomsky's, Katz
and Fodor attempted to develop a semantic
theory that would do what Chomsky's syntactic theories were designed to do: match the competence of the native speaker. In semantics this
meant developing a theory that would account
for the ability of native speakers to understand
the meaning of sentences, including ambiguity,
paraphrase, and semantic anomalies, the latter
referring to the deviant property of sentences such as "* Colorless green ideas sleep furiously" that render them meaningless in ordinary, nonmetaphorical use.
The semantic theory of Katz and Fodor and
related theories proposed by others focused only
on the meaning of the individual sentence in isolation both from surrounding sentences and from
the context in which it is used. Such a limitation,
however, contradicts the goal of matching the
competence of native speakers, as native speakers do indeed interpret sentences in context and
in fact are able to disambiguate sentences by interpreting them in the context in which they are
used. Contextual semantics and pragmatics offer explanations for this competency.
Contextual semantic theories allow for the
expansion of ordinary definitions of words to
incorporate semantic information upon which
native speakers can draw when they encounter
or use a word in a particular context. Raskin
uses the term script to refer to these more comprehensive semantic constructs. He suggests
that the word doctor carries with it not only
such semantic features as "+Adult," "+Human"
but also semantic information that incorporates
contextual details such as the activities (study
medicine, receive patients, diagnose and treat
diseases), places (medical school, hospital, doctor's office), and conditions (physical contact)
native speakers associate with the word. Context provides cues for which specific scripts one
might apply in a particular situation. Concepts
such as scripts thus account for the semantic
information that enables people to interpret
ambiguous sentences such as "The bill is large"
by applying contextual cues to select the appropriate meanings within the context of use.
Pragmatics, sometimes considered a separate linguistic discipline from semantics, typically
refers to several specific concepts concerning language users' understanding of how language is
used to communicate. The major concepts of
pragmatics are presupposition, speech acts, and
implicature. Presupposition refers to the assumptions or set of conditions that underlie a particular statement. For example, the sentence "The
accident was not my fault" presupposes that an
accident occurred and that someone might be at
fault. Speech act theory, proposed by Austin
(1962) and developed by Searle (1969) is designed to describe the function that sentences
perform in discourse. The three basic speech acts,
the locutionary act, the illocutionary act, and the
perlocutionary act refer respectively to the utterance, the intent of the utterance, and the effect
of the utterance. Since there is no correspondence
between syntactic structure and speech acts, the
same illocutionary act, for instance a request,
may be expressed by several locutionary acts.
Thus the question "Can you pass me the salt?"
and the command "Pass me the salt" and
the statement "This soup needs more salt" have
the same intention and are understood by
both speaker and hearer to produce the effect
of the hearer's passing the salt to the speaker.
These sentences also illustrate the concept of
implicature, developed by Grice (1975), which
refers to the use of sentences in nonliteral or
unconventional meanings. The sentence "This
soup needs more salt" only functions as a request
for salt if the appropriate circumstances, such as
the presence of a hearer who has access to salt,
exist. The same sentence may simply serve as an
observation or criticism if it is uttered in a different circumstance, such as to one's dinner companion in a restaurant where neither salt nor
server are immediately available. Grice's principles of bona fide communication (Quantity—
relate exactly as much information as necessary;
Quality—say only what you believe to be true;
Relation—speak to the point; and Manner—be
succinct) underlie the cooperative principle by
which the speaker tells the truth and the hearer
recognizes the intention and believes what is said.
Implicatures come about when the speaker deliberately violates one or more of the principles,
signals the violation to the hearer, and the hearer
recognizes the intended meaning of the violation.
A fourth pragmatic concept, related to the three
discussed thus far, is inference, which might be
thought of as the reader's (or hearer's) recognition of what is presupposed.
The previous discussion has focused on
principal disciplines of linguistics, but linguistics,
like rhetoric, is also an interdisciplinary field.
Other areas of linguistics include neurolinguis-
tics, which studies the physiological aspects of
language and the brain; historical linguistics; and
applied linguistics areas such as psycholinguis-
tics, text linguistics, discourse analysis, socio-
linguistics, and second language acquisition (including English as a Second Language). Of these
areas, the last four have the most direct connections with work in rhetoric and will be referred
to in the following discussion of applications of
linguistics to rhetoric and composition studies.
During the 1960s and 1970s, researchers in
rhetoric and composition developed applications
of the syntactic descriptions from Chomsky's
transformational generative grammar. Someresearchers believed that because transformational
generative grammar so successfully described
syntactic relationships, it might prove to be a
useful tool for teaching students to avoid errors
and to write more effective sentences. In oneregard this belief seems naive, as research has consistently demonstrated that formal grammar instruction has neither effect (for summaries of
numerous studies, see Braddock 1963 and Mellon 1969). Nevertheless, Chomsky's theories
provided the impetus for new research into the
relationship between instruction and grammar
and the teaching of writing.
One such study, that of Bateman and Zi-
donis (1964), reported that students instructed
in transformational grammar did reduce the
number of errors in their writing and, in addition, wrote sentences that contained a larger
number of transformations than did students
who did not receive such instruction. The apparently positive results of this study stimulated other research designed to identify more accurately
the specific causes for the improvement Bateman
and Zidonis reported. In particular, Mellon
(1969) and O'Hare (1973) questioned the extent
to which the growth reported could be attributed
to the formal instruction in transformational
grammar rather than to the actual practice of applying transformations. Following Chomsky,
Hunt (1964) and subsequently Mellon and
O'Hare argued that students possess the competence, that is, the inherent linguistic knowledge,
that allows them to recognize as grammatical
and to use most of the transformations Bateman
and Zidonis claimed to have taught. Theirresearch led to the development of pedagogies
based on sentence-combining, exercises in which
students combine a short series of sentences in
order to develop their ability to use a variety of
transformations. Though at the height of the
interest in sentence-combining claims were made
for its efficacy in improving students' writing in
a variety of ways, not just syntactically, sentence-
combining is currently seen as having a valuable
but limited function in helping writers practice
a variety of syntactic patterns they might not otherwise attempt to use and in alerting them to
numerous options of expressing themselves.
Both transformational grammar and
Kenneth Pike's tagmemic grammar have been
applied to rhetoric and composition studies as
facilitating invention. Francis Christensen's
"Generative Rhetoric of the Sentence" (1963)
and "Generative Rhetoric of the Paragraph"
(1965) loosely borrowed concepts from structuralist and transformational linguistics, which
he used to explain how syntactic structures he
called cumulative sentences encouraged the
"generation" of new ideas. Pike's tagmemics is
the origin both of theories of paragraph organization and of a heuristic, developed with
Alton Becker and Richard Young, based on
Pike's concepts of contrast, variation, and distribution. The work of Pike, Young, and Becker
was synthesized in their influential 1970 textbook Rhetoric: Discovery and Change. The
tagmemic heuristic presented there has been
adopted and adapted widely.
With the exception of Christensen's rather
metaphoric extension of transformational generative grammar to the generation of ideas in
writing and the applications of Pike's tagmemic
theory, most efforts to apply linguistic theory to
rhetoric prior to the 1980s focused primarily on
grammar and syntax. In a sense such an emphasis paralleled the notion of semanticists
Katz and Fodor, who, as explained above, argued that semantic theory could account for the
meaning of sentences in isolation but not for the
meaning of any sentence in context. However,
the work referred to earlier in semantics and
pragmatics, as well as work in text linguistics,
most done in the late 1960s and early 1970s,
suggested approaches to understanding both
meaning and structure in larger discourses, and
such research has been influential in rhetoric
and composition.
In particular, linguistic theories have been
applied to discourses longer than sentences as
means of analyzing and understanding cohesion
and coherence. Until the mid 1970s, cohesion
and coherence were often used interchangeably,
both referring either to a kind of vague sense of
wholeness or to a more specific set of relationships definable grammatically and lexically. The
work of Halliday and Hasan (1976) influenced
scholars and researchers in rhetoric and composition so that, by the early 1980s, the two terms
were distinguished. Cohesion is now understood to be a textual quality, attained through
the use of grammatical and lexical elements that
enable readers to perceive semantic relationships within and between sentences. Coherence
refers to the overall consistency of a discourse—
its purpose, voice, content, style, form, and so
on—and is in part determined by readers' perceptions of texts, dependent not only on linguistic and contextual information in the texts
but also on readers' abilities to draw upon other kinds of knowledge, such as cultural and
intertextual knowledge.
The most influential work on cohesion has
been Halliday and Hasan's Cohesion in English.
Halliday and Hasan identify three major types
of cohesion—grammatical cohesion, lexical
cohesion, and conjunction—and further classify
subgroups of each. Grammatical cohesion is
attained through the use of cohesive ties such as
pronouns, synonyms, comparatives, and definite articles, which link sentences but which do
not necessarily add new semantic information.
Lexical cohesion depends upon the semantic
relationship of one lexical item with another;
that is, any word is potentially cohesive but
becomes so only when it co-occurs with a se-
mantically similar word. Conjunction connectives, typically referred to as transitions, depend
neither upon reference to or replacement of
grammatical elements nor upon co-occurrence
with another lexical item. For example, in the
sentences "The students played soccer. Afterwards it rained" the conjunction afterwards
makes the two sentences more obviously cohesive by suggesting a specific temporal relationship between them. Each of these types of
cohesion can be understood in terms of the concept of presupposition, as the sentence containing the cohesive tie presupposes information
that does not appear in that sentence but that
is retrievable from the adjacent sentence.
The same kinds of cohesive ties that produce cohesion between two sentences produce
cohesion within larger texts. The use of conjunctions, repetition, synonyms, pronouns,
and other cohesive devices throughout a paragraph or longer discourse serve to create and
indicate cohesion. Analyses of cohesive patterns
in longer discourses, derived from the work of
text linguists and psycholinguists such as
van Dyke, Prince, and Clark and Clark, have
been applied in rhetoric by Witte and Faigley
(1981) and Witte (1983). In particular, Witte's
1983 "Topical Structure and Revision" provides an excellent summary of theories of topical structure from the Prague School, as well as
demonstrating the application of those theories
in composition.
Cohesion contributes to the coherence of
a text, but because coherence is determined by
readers' perceptions of texts, influenced both by
the texts themselves and the readers' world or
contextual knowledge, contextual semantics
and pragmatics also play a part in analyzing and
understanding coherence. In particular, script-
knowledge, inference, and presupposition contribute to the description of a text as coherent.
The presence of incompatible, redundant, or
irrelevant scripts in a text is an indication of its
incoherence. Texts that are underdetailed, requiring readers to make too many inferences,
and texts that are overdetailed, providing readers with information easily inferred, may also
be perceived to be incoherent (see Raskin and
Weiser 1987:212–16 for examples).
One other application of linguistics that
has not been mentioned thus far is directlyrelated to the fact that the goal of modern linguistics is to describe how language is used rather
than to prescribe its use. Dialectologists and
some sociolinguists study and describe patterns
of language use by specific groups of language
users. Their work has led to several important
recognitions: that the so-called standard dialect
(Standard American English) is an idealized
dialect that no one really speaks; that all dialects
are grammatical, though the grammatical patterns of dialects differ from one another; and
that the identification of any dialect as standard, privileged, or preferred is cultural, not
linguistic.
The previous discussion of linguistic applications to rhetoric and composition suggests
some ways in which linguistic concepts have
been borrowed to develop theories, pedagogical applications, and analytical techniques. The
contributions of linguistics to rhetoric and composition are thus significant, though not central.
And there are limits to linguistic applications to
rhetoric and composition, based on both the
descriptive nature of linguistics and the broader
concerns of rhetoric and composition. Because
linguistics is not prescriptive, it does not offer
judgments about language quality—that is, it
does not provide the basis for judging one of
two grammatical sentences as better than the
other. And because rhetoric and composition
are concerned not only with language but also
with the use of language in particular rhetorical situations, there are a number of extralin-
guistic dimensions of rhetorical effectiveness,
such as appropriateness for purpose and audience, the appropriateness of style, conformity to
rhetorical conventions for a particular type of
discourse, and so on, that linguistics cannot
address.
Irwin Weiser
Purdue University

<BibliographyCard>
Austin, John L. How to Do Things with
Words. New York: Oxford UP, 1962.
Bateman, D.R., and F.J. Zidonis. TheEffect of a
Knowledge of Generative Grammar upon the
Growth of Language Complexity. Columbus:
Ohio State U. U.S. Office of Education
Cooperative Research Project 1746,1964.
Braddock, Richard, et al. Research in Written
Communication. Urbana,IL: National
Council of Teachers of English, 1963.
Chomsky, Noam. Aspects of the Theory of
Syntax. Cambridge, MA: MIT P, 1965.______
. Syntactic Structures. The Hague:
Mouton, 1957.
Christensen, Francis. "A Generative Rhetoric
of the Paragraph." College Composition
and Communication 16 (1965): 144–56._______
. "A Generative Rhetoric of the Sentence." College Composition and Communication 14 (1963):155–61.
Grice, H. Paul. "Logic and Conversation."
Syntax and Semantics Vol. 3 Speech
Acts. Ed. Peter Cole and Jerry L. Morgan. New York: Academic, 1975. 41–
58.
Halliday, M.A.K., and Ruqaiya Hasan. Cohesion in English. London: Longmans, 1976.
Hunt, Kellogg W. Grammatical Structures
Written at Three Grade Levels. Urbana,
IL: National Council of Teachers of English, 1965.
Katz, Jerrold J., and Jerry A. Fodor. "The
Structure of a Semantic Theory." Language 39 (1963): 170–210.
Mellon, John C. Transformational Sentence-
Combining. Urbana,IL: National Council of Teachers of English, 1969.
O'Hare, Frank. Sentence-Combining: Improving Student Writing without FormalGrammar Instruction. Urbana, IL: National
Council of Teachers of English, 1973.
Raskin, Victor, and Irwin Weiser. Language
and Writing: Applications of Linguistics
to Rhetoric and Composition. Norwood,
NJ: Ablex, 1987.
Searle, John R. Speech Acts. Cambridge:
Cambridge UP, 1969.
Witte, Stephen P. "Topical Structure and Revision:
An Exploratory Study." College Composition and Communication 34 (1983): 313 –41.
Witte, Stephen P., and Lester Faigley. "Coherence, Cohesion, and Writing Quality. "
College Composition and Communication 32 (1981): 189–204.
Young, Richard E., Alton Becker, and Kenneth Pike. Rhetoric: Discovery and
Change. New York: Harcourt, 1970.
</BibliographyCard>

<SeeAlsoCard>
  <SeeAlsoLink href="/docs/coherence">Coherence</SeeAlsoLink>
  <SeeAlsoLink href="/docs/cohesion">Cohesion</SeeAlsoLink>
  <SeeAlsoLink href="/docs/pragmatics">Pragmatics</SeeAlsoLink>
</SeeAlsoCard>
