---
title: "Logos"
description: "Logical appeal ultimately understood as"
---

Logical appeal ultimately understood as
an appeal both to consistency and substantive reasons. As ethical appeal suggests nominally something to do with normative ethics,
logical appeal suggests something to do with
logical validity. But ethical appeal and logical
appeal as rhetorical notions are best directed at
understanding not what is good and true but
the best means of persuasion. Logic is less important for a rhetoric fashioned for general
audiences than for professional and technical
disciplines. What is striking about rhetoric studied in speech communication and composition
studies is the irrelevance of logical studies to
pedagogy. We see this division in the different
technical notions of argument found in rhetoric and in logic, a separation that goes back to
Aristotle. One needs to analyze the complexity
of the topic of logical appeal as a rhetorical
concept by viewing it in different contexts of
rhetorical, logical, and argumentation theory.
A good starting point to analyze the complexity of the concept is in the interpretations
of the Greek term logos, which is foundational
to classical Greek rhetoric. The fundamental
sense of logos isword. Logical appeal as
an appeal to words is an appeal to the consistency in our use and meaning of words. It is ad
hominem—that is, our appeals are to what
people say they believe and not to what we necessarily believe. If the meaning of what they say
is "such and such," then they are compelled
given their meaning to say "such and such."
Let's call a logical appeal to words and their
meaning an appeal to semantic consistency. To
say "John is a bachelor, and therefore he is
unmarried" is to say what is true of John on the
basis of the use of the term bachelor. Arguments
over semantic consistency are settled by semantic conventions of language usage. Disputes
over semantic consistency are resolved by mutually accepted interpretations of the uses of
words. Another way of characterizing the same
point about an appeal to logos as word is that
the conclusions of deductive arguments are contained in the premises. What you put into your
premises in words is what you get out. Or, expressed succinctly about computers, "garbage
in, garbage out."
But if we appeal to logos not asword,
but as logic, the basis of the appeal shifts from
semantic to syntactic consistency. In appealing to logos as logic—that is, logical relations
that exist between terms—we appeal not to the
meaning of sentences and their terms but to the
logical form that binds and relates terms. Logical relations exist within sentences between
terms, as in term logic, or they exist in the logical connections between sentences, as in sentence logic. Logical relations are generated by
the logical grammar within and between sentences—that is, by the logical operators and
formation rules that bind and relate phrase
structures and constitutive clauseswithin
sentences and that bind constitutive sentences
within arguments.
Traditionally, formal logic, which interprets such syntactic foundations of logicalappeal, little interests rhetoricians. Nevertheless,
logical operations are rhetorical concerns where
logical validity is at issue. Therefore, logic is of
concern in a rhetoric of the expert disciplines.
In contrast, in rhetoric for generalized audiences, there is little need for attention to logical form as such. Native speakers grasp logical form without undue attention to it. Just as
native speakers know the grammar of a language without technical formal grammatical
knowledge, so native speakers know the logic
of their language without technical formal logical knowlege. But speakers do call attention to
deductive fallacies by contrasting them with
analogous forms of argument where premises are true and conclusions false. Such a refu-
tational strategy appeals to an intuition of form,
not to logical rules.
Insofar as rhetorical arguments use gaps,
ellipses, and enthymemes, they operate in a context of presumptions. They never depend as do
logical arguments on what is explicitly stated.
Rather, rhetorical appeals sketch the form of
their arguments in a context of linguistic, communicative, and cultural presumptions that
audiences intuitively grasp. In contrast, logic
demands explicit rigor. Logic demands a full
display of logical form. Logic avoids the ambiguity to which rhetorical arguments are prone.
Note the ambiguity of the unquantified subject
term in "Italians are emotionally expressive."
Logic, unlike rhetoric, does not admit of presumption. Logic, to be fully rigorous, unlike
rhetoric, demands full and explicit, rigorous
annotations of the rules that govern operations.
Rarely would one give a rule of inference in
rhetorical argument to justify a conclusion.
Rhetorical arguments as appeals to presumptive
entailments are appeals to syntactic consistency
in a context of intuitively grasped communicative presumptions.
To clarify the overlapping and interrelated
contrasting concepts of rhetorical argument and
logical argument, the term argument has four
distinct but related uses. First we speak of argument as quarrel, or controversy. This is a
sociological interest in argument, a description
of social conflict and its companion violence. A
paradigm is a domestic quarrel. Second, there
is argument as appeal for the acceptance of a
claim. This is the use common to forensics and
argumentation. It is an appeal for the acceptance of a contention based upon what an audience accepts or is willing to accept. Importantly, rhetorical arguments look to beliefs of an
audience to effect changes in them. A paradigm
is a lawyer's appeal to a jury. Third, there
is argument as deductive argument, traditional
to logical studies. Deductive logic is the study
of strict entailments—that is, if the premises
are true it would be impossible, given the logical form of the argument, to deny the conclusion. A paradigm is a strict mathematical proof.
Fourth, there is argument as inductive, as giving evidence to support a probability. Inductive
arguments and their validity are the concern of
inductive logic and inferential statistics. A paradigm is gathering evidence in scientific experiments to confirm empirical hypotheses. Important to note in relating these four uses of "argument" is that we settle arguments as controversy by arguments as appeals using deductive
and/or inductive logical arguments.
Appeals to semantic and syntactic consistency are arguments appealing to embodied
meaning and logical structures in texts.
They focus on the meaning of the wording and
the presumptions behind the wording. But such
logical appeals are not focal to oratory
and public address, argumentation, and forensics. In such disciplines logical appeals are not
to logical grounds but to reasons presented as
premises, to logos as reason. The appeal is to
premises, warrants, evidence, facts, data, observations, backing, support, explanations, causes,
signs, commonplaces, principles, or maxims.
Insofar as the emphasis is on logos as reason,
logical appeal is to the substance of premises
and/or presumptions and not to meaning or
logical form.
The senses of what it is to give a reason are
much more numerous than the senses of what
it is to argue. Arguments give reasons. Explanations give reasons, but explanations may not
be logical appeals. Nor do all explanations provide us with reasons. Rather, explanations in the
general use of "explain" respond to interests
that an audience might have expressed in the
form of questions. Explanations as answers to
questions differ widely. We might explain what
happened, what something is like, how it happened, how something works, when it occurred,
in what manner, what caused it, who did it, or
for what purpose. Explanations as answers to
questions, unless they are theoretical explana-
tions, usually involve no logical arguments.
Theoretical explanations as premises logically
entail the facts to be explained. Facts as entailed
conclusions of theoretical explanations are not
open to contention. Explanations often exist in
communicative contexts where no rhetorical
logical appeal is being made. Yet audiences on
many occasions demand justification for explanations. They incur a burden ofproof. Explanations in such cases are what we argue for.
Narration, description, and exposition as
explanations are usually responses, not appeals.
Yet often these modes of discourse are used to
make appeals indirectly. As such, narration and
description function as logical appeals. Note
that we question the purpose of explanations.
"Why are you telling me that?" "Why are you
explaining that to me?" "Why are you pointing
that out to me?" Thus, modes often contextu-
ally imply claims and contentions. Note that my
giving you my reasons for my believing something may indirectly or contextually imply that
you ought to believe the same thing for the same
reasons. Thus, exposition indirectly appeals by
contextual implication. For example, literary
discourse, historical explanation and narrative,
journalistic description, and technological explanations can function contextually as indirect
logical appeals. Note that some treatments of
enthymemes in logic texts admit as enthymemes
explicit premises with implicitly understood
conclusions.
Probably the most important epistemologi-
cal sense of logos as reason is as fact or data,
reason as inductive argument, that is, as evidential support for the probability of an hypothesis.
Inductive argument as appeal gives evidence to
support the probability of an hypothesis. With
the exception of induction by enumeration,
inductive arguments never produce absolute
certainty. All hypotheses as conclusions of
inductive appeals are potentially open to dis-
confirmation. Aristotle used enthymemes and
examples as the basis for rhetorical arguments.
As such, for Aristotle there could be no question
of certainty for the conclusions of rhetorical
arguments. A problem for Aristotle is how to
use probabilistic premises effectively to gain acceptance for contentions that seem only probably true. Using Aristotle's terms, how do we
distinguish what is essential from what isaccidental in species or individual substances?
First, logical appeal in rhetoric for Aristotle
in arguing from probabilistic premises is opposed to scientific demonstration, where argument is from certainty to certainty. One interpretation of enthymemes in Aristotle is that they
are arguments with probabilistic premises entailing probabilistic conclusions. In contrast for
him, the theoretical sciences aim at strict proof
with scientific or syllogistic demonstration.
Second, rhetorical induction for Aristotle
is argument from example. Examples allow inductive generalization from "some" to "all,"
induction by instantiation. Or, interestingly, an
example allows for inductive generalization
from "one" typical or representative example
or sample to "all." What is missing in Aristotle's
account of induction is any numerical quantitative sense of generalized tendencies from aggregations or samples. Missing is any sense
of inductive argument by statistical inference.
Aristotle's generalizations from common-sense
tendencies display a lack of any quantitative
concept of probability. Aristotle's deficiency
merely reflects the deficiencies of vernacular
languages in ascribing with any precision calculations of probabilities. It is the poverty of ordinary language to have few quantitative conceptions to assess probability. For this reason
most inductive arguments using natural language are prone to misleading and deceptive
assessments of probabilities. As most rhetorical
arguments are saturated with inductive arguments by instantiation of instances, examples,
cases, or samples, induction in natural languages is prone to hasty generalizations and/or
misleading, selective, and deceptive presentations of data.
Modern conceptions of causality too are
based upon theories warranted by induction by
instantiation of a number of confirming instances, where the correlation of factors in a
number of instances in an observation sample
is generalized to obtain for a target population.
The degree to which we warrant the causal or
empirical hypotheses generalized over a target
population is relative to the number of instances
that correlate in the observational sample.
Inductive warrant for empirical generalizations comes in two flavors: invariant
correlations and a probable frequency of a
correlation. Importantly, inductive support for
statements about invariance are always probable. Equally inductive support for statements
about the ranges of probabilities of a correlation are also only probable, a probability of
a probability. Apart from induction by enumeration, inductive arguments by instantiation
never arrive at logically necessary conclusions
about invariance or about probabilistic correlations.
Moreover, besides appeals using warrants
by induction from instantiation, we may reinforce the probability of any hypothesis byinduction by systematic coherence. Any empirical
generalization logically entailed by or derived
from another hypothesis whose probability has
been established has its probability corroborated by that hypothesis. Established theory
through its derived tested hypotheses adds to
the probability of those hypotheses. Logical
coherence thus enhances probabilities.
Insofar as Aristotle presumes examples
typical or exemplary, as natural kinds or species, there is a presumption ofinvariance in
Aristotle. What would warrant this invariance?
But as indicated in modern conceptions of inductive empirical generalization, hypotheses
about invariance are always probable. To establish any presumption of invariance, there must
exist a prior inductively and empirically justified argument for the probability of that presumption. If in argumentation from example we
grant the presumption ofinvariance, then one
sample or example will do. We assume that all
cadavers are anatomically alike, so we assume
that any detail in dissection of a cadaver would
be like any other cadaver. By granting the presumption of invariance from past experience in
anatomical studies, we avoid hasty generalization. Arguments from a single example or case
history require such a presumption ofinvariance to avoid any charge of hasty generalization.
Many traditional logical or rhetorical fallacies are simply confusions about whether appeals are deductive or inductive. Insofar as most
rhetorical appeals are inductive, it is rhetorically
necessary to be careful about modalities and
quantifiers to indicate whether an argument is
inductive or deductive. Overstatement and hyperbole tend to confuse these issues. Essential-
ism and views about natural kinds also tend to
blur modal distinctions. That a type is essential
or a natural kind is a presumption of invariance
that needs to be inductively warranted.
Another distinct kind of reason as distinct
from the above accounts of theoretical reason,
that is, epistemological accounts of reasoning,
is practical reason, that is, axiological accounts
of reasoning. This distinction is strikingly made
in speech communication between arguments for propositions of fact and arguments
for propositions of value or policy arguments.
Just as we draw distinctions about fact—( 1 ) observations, (2) generalizations about observations, and (3) theoretical explanations of generalizations about observations—so too we can
draw distinctions about value—(1) values defined by interests, (2) moral and ethical value,
(3) social and political value, and (4) aesthetic
value. Importantly, we argue for all these distinctions of fact and value differently, thus multiplying the modes and complexities of logical
appeal.
Are ethical and emotive appeals rational?
Questions about values are arguably connected
to questions of feelings and expert authority.
Inductively, we might want to say it is rational
to trust one's feelings, or it is sometimes rational to trust the credibility or expertise or authority of another person. In this case, rational
means giving inductive reasons to support trust
or confidence in the validity of our feelings or
our trust in others. Such trust, insofar as it is
open to disconfirmation, makes such appeals
arguments from probabilities. And again, insofar as such trust may be based upon lived experience, such presumptions about feeling and
character are reliably rational. Thus, a taxonomy of appeals as logical, ethical, and emotive as distinct categories breaks down as we
assess rationally the persuasive value of ethos
and pathos. Using inductive arguments, we may
justify the validity of an appeal to our feelings
or appeals to authority. Note in particular that
an ad hominem abusive need not be a fallacy
insofar as it is an inductive argument that discounts an appeal to authority.
It is the character of many commonplaces,
proverbs, and maxims of common wisdom to
appear trustworthy and highly probable. They
are confirmed inductively by common sense.
Consequently, common-sense arguments tend
to be highly effective rhetorically. Such argument tends to be conservative, as it appeals to
traditional or cultural wisdom. Moreover, conventional wisdom is often embodied in language usage. It too reflects conventional and
traditional values.
But among traditions of cultural wisdom
also are maxims or proverbs about principles of
justice, prudence, and personal value such as
liberty and property. If you are trying to convince me that I am wrong about my actions,
three lines of argument prove rhetorically quite
effective against me. First, what I am doing is
unfair. Second, what I am doing is not in the
long-run good of most people. Third, what I am
doing is hurting myself. The first line is about
justice. The latter two are about types of prudence: prudence in maximizing public good and
prudence in maximizing private good. Insofar
as an audience can agree on principles of fairness, public good, and self-interest—and about
the priorities of one over the other—arguments
about values and policy are rational in the sense
that they follow logically from accepted principles. Such arguments form the bread and butter of ethical and political argumentation.
Logical appeal using figures of speech
such as metaphor, allusions, or analogies are
not based on interpretations of literal terms
but on what is contextually implied by such
figures. There is in the use of figures, allusions, and analogies in rhetorical contexts
and situations a mode of discourse directing
attention to a wealth of contextual implications that literal language has no time to
take the pains to specify. It is the function
of figurative logical appeals to call attention to
a ground of presumption in the context of a
rhetorical situation. Thus the rhetor has to
lay the foundation of a logical appeal in
presumption both literally and figuratively
by a number of different speech acts, such as
reminding or noting, giving testimony or assuring, and citing the testimony of others orreporting the expertise of others. The first pair
essentially give focus to what is presumptively available in the audience's experience,
the second on the presumptive ethos of
the rhetor, and the third on the presumption that the audience is granting credibility
and expertise to those cited.
A logical appeal thus ultimately must be
understood as an appeal both to consistency
and substantive reasons. It is the function of the
rhetor to appeal to what is presumptivelyacceptable by an audience to effect change in an
audience's acceptances and commitments. In
using all the available means of persuasion, the
rhetor uses every means to call attention to a
presumptively acceptable ground that will justify to an audience contentions at issue. What
seems rhetorically fundamental in logical appeal
is using words literally, figuratively, suggestively,
and by means of presumption to focus on a
ground of audience acceptance, a ground that
will reasonably alter what an audience accepts.
Unlike the case in logic, this is not a verbally
explicit enterprise.
